.TH "MCAL Directory Reference" 3 "Tue Sep 13 2022" "Trafic Light LED" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MCAL Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDIO Driver\fP"
.br
.ti -1c
.RI "directory \fBTimer\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBInterrupts\&.h\fP"
.br
.in -1c
