.TH "Service/Delay Directory Reference" 3 "Tue Sep 13 2022" "Trafic Light LED" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Service/Delay Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdelay_ms\&.c\fP"
.br
.RI "Implements Delays to be used in the program using the Timer driver\&. "
.ti -1c
.RI "file \fBdelay_ms\&.h\fP"
.br
.in -1c
