.TH "App Directory Reference" 3 "Tue Sep 13 2022" "Trafic Light LED" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBapp\&.h\fP"
.br
.RI "Coniatins the needed definition of the macros, variables and functions used by the application\&. "
.in -1c
