.TH "ECUL/Button Driver Directory Reference" 3 "Tue Sep 13 2022" "Trafic Light LED" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ECUL/Button Driver Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbutton\&.c\fP"
.br
.RI "button Driver that intialize and operates the DIO Pins as inputs connected to buttons "
.ti -1c
.RI "file \fBbutton\&.h\fP"
.br
.RI "button Driver that intialize and operates the DIO Pins as inputs connected to buttons "
.in -1c
