.TH "Test_Dio.h" 3 "Tue Sep 13 2022" "Trafic Light LED" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test_Dio.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPORT_E\fP   'E'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTRAFF_DIO_001\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_002\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_003\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_004\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_005\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_006\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_007\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_008\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_009\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_010\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_011\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_012\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_013\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_014\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_015\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_016\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_017\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_018\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_019\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_020\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_021\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_022\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_023\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_024\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_025\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_026\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_027\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_028\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_029\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_030\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_031\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_032\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_033\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_034\fP ()"
.br
.ti -1c
.RI "void \fBTRAFF_DIO_035\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PORT_E   'E'"

.SH "Function Documentation"
.PP 
.SS "void TRAFF_DIO_001 ()"

.SS "void TRAFF_DIO_002 ()"

.SS "void TRAFF_DIO_003 ()"

.SS "void TRAFF_DIO_004 ()"

.SS "void TRAFF_DIO_005 ()"

.SS "void TRAFF_DIO_006 ()"

.SS "void TRAFF_DIO_007 ()"

.SS "void TRAFF_DIO_008 ()"

.SS "void TRAFF_DIO_009 ()"

.SS "void TRAFF_DIO_010 ()"

.SS "void TRAFF_DIO_011 ()"

.SS "void TRAFF_DIO_012 ()"

.SS "void TRAFF_DIO_013 ()"

.SS "void TRAFF_DIO_014 ()"

.SS "void TRAFF_DIO_015 ()"

.SS "void TRAFF_DIO_016 ()"

.SS "void TRAFF_DIO_017 ()"

.SS "void TRAFF_DIO_018 ()"

.SS "void TRAFF_DIO_019 ()"

.SS "void TRAFF_DIO_020 ()"

.SS "void TRAFF_DIO_021 ()"

.SS "void TRAFF_DIO_022 ()"

.SS "void TRAFF_DIO_023 ()"

.SS "void TRAFF_DIO_024 ()"

.SS "void TRAFF_DIO_025 ()"

.SS "void TRAFF_DIO_026 ()"

.SS "void TRAFF_DIO_027 ()"

.SS "void TRAFF_DIO_028 ()"

.SS "void TRAFF_DIO_029 ()"

.SS "void TRAFF_DIO_030 ()"

.SS "void TRAFF_DIO_031 ()"

.SS "void TRAFF_DIO_032 ()"

.SS "void TRAFF_DIO_033 ()"

.SS "void TRAFF_DIO_034 ()"

.SS "void TRAFF_DIO_035 ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Trafic Light LED from the source code\&.
