.TH "Types.h" 3 "Tue Sep 13 2022" "Trafic Light LED" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Types.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNULL\fP   0 /** Define NULL in the program*/"
.br
.ti -1c
.RI "#define \fBTRUE\fP   0xAA"
.br
.RI "Define the true Value\&. "
.ti -1c
.RI "#define \fBFALSE\fP   0x55"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBStatus\fP \fBStatus\fP"
.br
.RI "Enum showing the state of the function\&. "
.ti -1c
.RI "typedef unsigned char \fBuint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuint16_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBStatus\fP { \fBOk\fP, \fBNot_ok\fP }"
.br
.RI "Enum showing the state of the function\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FALSE   0x55"

.SS "#define NULL   0 /** Define NULL in the program*/"

.SS "#define TRUE   0xAA"

.PP
Define the true Value\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef enum \fBStatus\fP \fBStatus\fP"

.PP
Enum showing the state of the function\&. 
.SS "typedef unsigned int \fBuint16_t\fP"

.SS "typedef unsigned char \fBuint8_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBStatus\fP"

.PP
Enum showing the state of the function\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOk \fP\fP
.TP
\fB\fINot_ok \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Trafic Light LED from the source code\&.
